import { useState, useMemo } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useSupabaseTable } from '../../lib/useSupabaseTable';
import { validateRequired, validateCurrency, validateDateRange, runValidators } from '../../lib/validation';
import { isSkEditor } from '../../utils/roles';
import FormField from '../../components/ui/FormField';
import ErrorBanner from '../../components/ui/ErrorBanner';
import Badge from '../../components/ui/Badge';
import { FolderKanban, Plus, Search, Filter, Edit3, Trash2, X, Calendar, DollarSign, Tag } from 'lucide-react';

const STATUSES = ['planned', 'ongoing', 'completed', 'cancelled'];
const CATEGORIES = ['Youth Development', 'Sports & Recreation', 'Education & Training', 'Health & Wellness', 'Environment', 'Livelihood', 'Leadership & Governance', 'Other'];
const EMPTY = { title: '', description: '', category: CATEGORIES[0], budget_amount: '', start_date: '', end_date: '', status: 'planned' };

export default function SKPrograms() {
  const { profile } = useAuth();
  const canEdit = isSkEditor(profile?.role);
  const { rows, loading, error, insertRow, updateRow, deleteRow } = useSupabaseTable('sk_programs', profile?.barangay_id);
  const [form, setForm] = useState(EMPTY);
  const [editingId, setEditingId] = useState(null);
  const [fieldErrors, setFieldErrors] = useState({});
  const [submitError, setSubmitError] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [modalOpen, setModalOpen] = useState(false);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [categoryFilter, setCategoryFilter] = useState('all');

  const openModal = (row = null) => { setForm(row ? { title: row.title, description: row.description || '', category: row.category || CATEGORIES[0], budget_amount: row.budget_amount ? String(row.budget_amount) : '', start_date: row.start_date || '', end_date: row.end_date || '', status: row.status || 'planned' } : EMPTY); setEditingId(row?.id || null); setFieldErrors({}); setSubmitError(''); setModalOpen(true); };
  const closeModal = () => { setModalOpen(false); setEditingId(null); setForm(EMPTY); setFieldErrors({}); setSubmitError(''); };
  const handleSubmit = async (event) => { event.preventDefault(); const { errors, isValid } = runValidators(form, { title: (value) => validateRequired(value, 'Title'), budget_amount: (value) => value ? validateCurrency(value, 'Budget') : '' }); const dateError = validateDateRange(form.start_date, form.end_date); if (dateError) errors.end_date = dateError; setFieldErrors(errors); if (!isValid || dateError) return; setSubmitting(true); const payload = { ...form, budget_amount: form.budget_amount ? Number(String(form.budget_amount).replace(/,/g, '')) : 0, created_by: profile.id }; const result = editingId ? await updateRow(editingId, payload) : await insertRow(payload); setSubmitting(false); if (result.error) setSubmitError(result.error); else closeModal(); };
  const handleDelete = async (id) => { if (!window.confirm('Delete this SK program?')) return; const result = await deleteRow(id); if (result.error) setSubmitError(result.error); };
  const stats = useMemo(() => ({ total: rows.length, ongoing: rows.filter((row) => row.status === 'ongoing').length, completed: rows.filter((row) => row.status === 'completed').length, budget: rows.reduce((sum, row) => sum + Number(row.budget_amount || 0), 0) }), [rows]);
  const filteredRows = rows.filter((row) => (row.title?.toLowerCase().includes(search.toLowerCase()) || row.description?.toLowerCase().includes(search.toLowerCase()) || row.category?.toLowerCase().includes(search.toLowerCase())) && (statusFilter === 'all' || row.status === statusFilter) && (categoryFilter === 'all' || row.category === categoryFilter));

  return <div className="space-y-6 max-w-6xl">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-3xl font-bold text-civic-navy flex items-center gap-3"><FolderKanban className="w-8 h-8 text-civic-emerald" /> SK Programs & Projects</h1><p className="text-slate-600 text-sm mt-1">Manage youth-focused programs, project budgets, timelines, and status.</p></div>{canEdit && <button onClick={() => openModal()} className="btn-emerald"><Plus className="w-4 h-4" /> Add New SK Program</button>}</div>
    <ErrorBanner message={error || submitError} />
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><div className="card"><p className="text-xs font-bold text-slate-500 uppercase">Total SK Programs</p><p className="text-2xl font-bold text-civic-navy mt-1">{stats.total}</p></div><div className="card"><p className="text-xs font-bold text-slate-500 uppercase">Ongoing Youth Projects</p><p className="text-2xl font-bold text-emerald-700 mt-1">{stats.ongoing}</p></div><div className="card"><p className="text-xs font-bold text-slate-500 uppercase">Completed Projects</p><p className="text-2xl font-bold text-blue-700 mt-1">{stats.completed}</p></div><div className="card"><p className="text-xs font-bold text-slate-500 uppercase">Program Budgets</p><p className="text-xl font-bold text-amber-800 mt-1">₱{stats.budget.toLocaleString(undefined, { maximumFractionDigits: 0 })}</p></div></div>
    <div className="card p-4 flex flex-col md:flex-row gap-3"><div className="relative flex-1"><Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-3" /><input className="input-field pl-10" placeholder="Search SK programs, projects, categories..." value={search} onChange={(event) => setSearch(event.target.value)} /></div><div className="flex items-center gap-2"><Filter className="w-4 h-4 text-slate-400" /><select className="input-field text-xs font-semibold" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="all">All Statuses</option>{STATUSES.map((status) => <option key={status} value={status}>{status}</option>)}</select><select className="input-field text-xs font-semibold" value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value)}><option value="all">All Youth Categories</option>{CATEGORIES.map((category) => <option key={category} value={category}>{category}</option>)}</select></div></div>
    {modalOpen && <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm flex items-center justify-center p-4 z-50"><div className="bg-white rounded-2xl shadow-card-hover border border-slate-200 p-6 max-w-xl w-full space-y-6 max-h-[90vh] overflow-y-auto"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><div><h2 className="text-xl font-bold text-civic-navy"><FolderKanban className="w-5 h-5 inline text-civic-emerald" /> {editingId ? 'Edit SK Program' : 'Add New SK Program'}</h2><p className="text-xs text-slate-500 mt-1">Define youth objectives, budget, timeline, and program status.</p></div><button onClick={closeModal} className="text-slate-400"><X className="w-5 h-5" /></button></div><form onSubmit={handleSubmit} className="space-y-4"><FormField label="Program / Project Title" placeholder="e.g. Youth Sports Development 2026" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} error={fieldErrors.title} /><div className="grid sm:grid-cols-2 gap-3"><FormField as="select" label="Youth Program Category" value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}>{CATEGORIES.map((category) => <option key={category} value={category}>{category}</option>)}</FormField><FormField label="Budget (₱)" placeholder="e.g. 50,000.00" value={form.budget_amount} onChange={(event) => setForm({ ...form, budget_amount: event.target.value })} error={fieldErrors.budget_amount} /></div><div className="grid sm:grid-cols-3 gap-3"><FormField type="date" label="Start Date" value={form.start_date} onChange={(event) => setForm({ ...form, start_date: event.target.value })} /><FormField type="date" label="End Date" value={form.end_date} onChange={(event) => setForm({ ...form, end_date: event.target.value })} error={fieldErrors.end_date} /><FormField as="select" label="Status" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}>{STATUSES.map((status) => <option key={status} value={status}>{status}</option>)}</FormField></div><FormField as="textarea" rows={3} label="Description & Objectives" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /><ErrorBanner message={submitError} /><div className="flex justify-end gap-2 pt-4 border-t border-slate-100"><button type="button" onClick={closeModal} className="btn-secondary">Cancel</button><button type="submit" disabled={submitting} className="btn-emerald">{submitting ? 'Saving…' : editingId ? 'Save Changes' : 'Save SK Program'}</button></div></form></div></div>}
    <div className="grid gap-4">{loading && <p className="text-slate-400 text-center py-8">Loading SK programs…</p>}{!loading && filteredRows.length === 0 && <div className="card text-center py-12 text-slate-500">No SK programs match your search criteria.</div>}{filteredRows.map((row) => <div key={row.id} className="card hover:border-slate-200 transition-all space-y-3"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2"><div className="flex flex-wrap items-center gap-3"><h3 className="text-lg font-bold text-civic-navy">{row.title}</h3><Badge status={row.status} /></div>{canEdit && <div className="flex items-center gap-2"><button onClick={() => openModal(row)} className="p-1.5 text-slate-600"><Edit3 className="w-4 h-4" /></button><button onClick={() => handleDelete(row.id)} className="p-1.5 text-rose-500"><Trash2 className="w-4 h-4" /></button></div>}</div><p className="text-sm text-slate-600">{row.description || 'No description provided.'}</p><div className="flex flex-wrap items-center gap-3 text-xs font-semibold border-t border-slate-100 pt-2"><span className="flex items-center gap-1 text-slate-700 bg-slate-100 px-2.5 py-1 rounded-md"><Tag className="w-3.5 h-3.5 text-civic-emerald" /> {row.category || 'Youth Program'}</span><span className="flex items-center gap-1 text-emerald-700 bg-emerald-50 px-2.5 py-1 rounded-md"><DollarSign className="w-3.5 h-3.5" /> ₱{Number(row.budget_amount || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</span><span className="flex items-center gap-1 text-slate-500 ml-auto"><Calendar className="w-3.5 h-3.5" /> {row.start_date || 'TBD'} {row.end_date && `– ${row.end_date}`}</span></div></div>)}</div>
  </div>;
}
